# based on https://github.com/heckenmann/dse-docker-compose/blob/master/docker-compose.yml
version: '3.8'

services:
  # I don't think it works, and for now at least kind of is slowing down development, so just backlog adding this into docker for now
  # play-server:
  #   build:
  #     context: ./play-app
  #   hostname: i-graph-play-server
  #   container_name: i-graph-play-server
  #   environment:
  #     - "DSE_SEEDS=dse"
  #       # cap_add:
  #       #   - IPC_LOCK
  #       # ulimits:
  #       #   memlock: -1
  #   volumes:
  #     # https://kelda.io/blog/docker-volumes-for-development/
  #     - ${INTERTEXTUALITY_GRAPH_PLAY_API_DIR:-./play-app}:/app
  #   ports:
  #     - 9000:9000

  dse:
    image: datastax/dse-server:6.8.3-ubi7-1
    hostname: dse
    container_name: i-graph-dse
    environment:
      - "DS_LICENSE=accept"
      - "SEEDS=dse,dse-01"
    command: [
      "-k",
      "-s",
      "-g"
    ]
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - "9042:9042"
    networks: 
      - i-graph

        # dse-01:
        #   image: datastax/dse-server:6.8.3-ubi7-1
        #   environment:
        #     - "DS_LICENSE=accept"
        #     - "SEEDS=dse,dse-01"
        #   command: [
        #     "-k",
        #     "-s",
        #     "-g"
        #   ]
        #   cap_add:
        #   - IPC_LOCK
        #   ulimits:
        #     memlock: -1
        #   networks: 
        #     - i-graph

        # dse-opscenter:
        #   image: datastax/dse-opscenter:6.8.4
        #   environment:
        #     - "DS_LICENSE=accept"
        #   ports:
        #     - "8888:8888"
        #   networks: 
        #     - i-graph
      
  dse-studio:
    image: datastax/dse-studio:6.8.2
    container_name: i-graph-dse-studio
    environment:
      - "DS_LICENSE=accept"
    depends_on:
      - dse
    ports:
      - "9091:9091"
    networks: 
      - i-graph
networks:
  i-graph:
    external: true
